ALTER TABLE TRANSACTIONS DROP COLUMN TRANSACTION_ID;

ALTER TABLE TRANSACTIONS DROP ACCOUNT_ID;

ALTER TABLE TRANSACTIONS DROP TRANSACTION_DATE;

ALTER TABLE TRANSACTIONS DROP TRANSACTION_AMOUNT;

ALTER TABLE INVENTORY_TRACKING DROP ITEM_NAME;

ALTER TABLE INVENTORY_TRACKING DROP product_id;

ALTER TABLE INVENTORY_TRACKING DROP product_sku;